name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run vitest
        run: bun run test:coverage
      - name: Run lint
        run: bun run lint
      - name: Run typecheck
        run: bun run typecheck
      - name: Run build
        run: bun run build
